# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

db.user=TAE_NOTIFICA
db.password=C3wr0l3$
db.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@10.203.26.165:1525/vtct