# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
# Configuraci\u00f3n de conexi\u00f3n a Informix
DB_DRIVER=oracle.jdbc.driver.OracleDriver
DB_URL=jdbc:oracle:thin:@10.191.143.5:1525/vtct
DB_USER=TAE_NOTIFICA
DB_PASSWORD=keFa#h4PtUz7Hds$
#MAQUETA
#DB_DRIVER=com.informix.jdbc.IfxDriver
#DB_URL=jdbc:informix-sqli://10.152.120.130:40000/des_bolsac:INFORMIXSERVER=online_des
#DB_USER=svbolsa
#DB_PASSWORD=TEm@qu3t4
#prod 
#_DB_DRIVER=com.informix.jdbc.IfxDriver
#_DB_URL=jdbc:informix-sqli://10.152.120.21:41168/bolsabd:INFORMIXSERVER=bolsa_grpa
#_DB_USER=taenotifica
#_DB_PASSWORD=PEm@q13t4

#_RUTA_CONTACTOS=/cem/mon/vtae/PRODUCCION/OTROS/Notificaciones/Factura_Unificado/conf/ContactosFactNva.txt

#_RUTA_LOGS=/cem/mon/vtae/PRODUCCION/OTROS/Notificaciones/Factura_Unificado/log